

### Haetaan blogit
GET http://localhost:3003/api/blogs

### Lisätään
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Kissan Blogi",
  "author": "Tiku T Kissa",
  "url": "https://Kissan blogi",
  "likes": 5
}
